name: "a2c"

agent:
  _partial_: true
  _target_: ev_charging.a2c.ActorCriticAgent
  device: "cpu"
  target_update_freq: 100
  learning_starts: 5_000
  eps_start: 1.0
  eps_end: 0.005
  eps_decay_steps: 350_000
  gamma: 0.99
  learning_rate: 5e-4
  memory_size: 500_000
  model_hidden_dim: 64
  model_nb_layers: 3
