name: "a2c"

agent:
  _partial_: true
  _target_: ev_charging.a2c.ActorCriticAgent
  device: "cpu"
  
  gamma: 0.99

  actor_lr: 5e-4
  critic_lr: 5e-4

  model_hidden_dim: 64
  model_nb_layers: 3

  # Optional 
  entropy_coef: 0.01
  normalize_rewards: false
     
