name: "a2c"

agent:
  _partial_: true
  _target_: ev_charging.a2c.ActorCriticAgent   # <-- your real import path
  device: "cpu"
  gamma: 0.99
  actor_lr: 0.00003
  critic_lr: 0.0001
  model_hidden_dim: 64
  model_nb_layers: 3
  entropy_coef: 0.01         # can be 0.0 if you don't want entropy
  normalize_rewards: true
