name: "ga"

agent:
  _partial_: true
  _target_: ev_charging.ga.GeneticAlgorithmEV
  genome_dim: 6
  population_size: 20
  n_generations: 10
  elite_frac: 0.2
  mutation_std: 0.1
  mutation_prob: 0.3
  n_eval_episodes: 30
