defaults:
  - _self_
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}/${experiment.type}
experiment:
  type: "explore_env"
logging:
  fps: 4
exploration:
  nb_episodes: 1
  seed: 42
env:
  _partial_: true
  _target_: ev_charging.env.EvChargingEnv
  device: "cpu"
  advance_until_next_request: true
  nb_stations: 3
  min_charge_speed: 20
  max_charge_speed: 20
  min_charge_speed_sharpness: 3
  max_charge_speed_sharpness: 3
  min_chargers_per_station: 3
  max_chargers_per_station: 3
  min_travel_time_to_station: 1
  max_travel_time_to_station: 1
  max_nb_cars_traveling_to_station: 2
  max_nb_cars_waiting_at_station: 1
  min_car_capacity: 200
  max_car_capacity: 200
  max_car_init_soc: 0.7
  station_full_penalty: 1.0
  min_steps_between_arrivals: 1
  max_steps_between_arrivals: 1
  max_steps: 1000