defaults:
  - _self_
  - algo: random
  - env: train

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}/${experiment.type}

experiment:
  type: "test_agent"

logging:
  prefix: "test"

eval:
  seed: 753
  n_eval_episodes: 100

  # Change these paths to match real file locations !!!!!
  weights:
    - "outputs/train_ga/2025-12-15/12-03-02/ga_best_genome_seed_42.pt"
    - "outputs/2025-12-14_22-50-46/ddqn_train_agent/weights/ddqn_500000.pt"
    - "outputs/2025-12-14_22-50-46/ddqn_train_agent/weights/ddqn_500000.pt"
