defaults:
  - _self_
  - algo: random
  - env: train

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}/${experiment.type}

experiment:
  type: "test_agent"

logging:
  prefix: "test"
  video_rollouts: 1 
  video_fps: 4

eval:
  # Global seed for python/torch random generators (not the env)
  global_seed: 753
  # seeds for different env layouts
  test_seeds: [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]
  n_eval_episodes: 100
  weights:
    - "weights/ddqn/ddqn_seed_0_stepp_500000.pt"
    - "weights/ddqn/ddqn_seed_1_stepp_500000.pt"
    - "weights/ddqn/ddqn_seed_2_stepp_500000.pt"
    - "weights/ddqn/ddqn_seed_3_stepp_500000.pt"
    - "weights/ddqn/ddqn_seed_4_stepp_500000.pt"