defaults:
  - _self_
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}/${experiment.type}_${env.name}
experiment:
  type: "test_ddqn"
logging:
  fps: 4
testing:
  nb_episodes: 1
agent:
  method: "ddqn"
  weights_paths:
    - "trained_agent_weights_0.pt"
    - "trained_agent_weights_1.pt"
    - "trained_agent_weights_2.pt"
env:
  name: "EvChargingEnv"
  env_config:
    device: "cpu"
    seed: 42
    nb_stations: 5
    min_charge_speed: 1
    max_charge_speed: 5
    min_charge_speed_sharpness: 1
    max_charge_speed_sharpness: 4
    min_chargers_per_station: 2
    max_chargers_per_station: 6
    min_travel_time_to_station: 20
    max_travel_time_to_station: 100
    max_nb_cars_traveling_to_station: 10
    max_nb_cars_waiting_at_station: 10
    min_car_capacity: 100
    max_car_capacity: 500
    max_car_init_soc: 0.8
    station_full_penalty: 10.0
    min_steps_between_arrivals: 2
    max_steps_between_arrivals: 5
    max_steps: 120