_partial_: true
_target_: ev_charging.env.EvChargingEnv
device: "cpu"
advance_until_next_request: true
nb_stations: 4
min_charge_speed: 2
max_charge_speed: 10
min_charge_speed_sharpness: 1
max_charge_speed_sharpness: 5
min_chargers_per_station: 1
max_chargers_per_station: 4
min_travel_time_to_station: 4
max_travel_time_to_station: 20
min_mean_travel_time_to_station: 6
max_mean_travel_time_to_station: 12
min_std_travel_time_to_station: 0.25
max_std_travel_time_to_station: 3.0
max_nb_cars_traveling_to_station: 4
max_nb_cars_waiting_at_station: 2
min_car_capacity: 300
max_car_capacity: 600
max_car_init_soc: 0.6
min_steps_between_arrivals: 1
max_steps_between_arrivals: 4
max_steps: 500
reward_congestion_weight: -0.5
reward_urgency_weight: -0.1
reward_energy_weight: 0.3
reward_charged_cars_weight: 0.5
reward_station_full_penalty: 3.0